revamp git_export_all_file_versions

diff --git a/bin/git_export_all_file_versions b/bin/git_export_all_file_versions
--- a/bin/git_export_all_file_versions
+++ b/bin/git_export_all_file_versions
@@ -1,54 +1,42 @@
-#!/bin/bash
+#!/bin/sh
 
-# we'll write all git versions of the file to this folder:
+# based on script provided by Dmitry Shevkoplyas at http://stackoverflow.com/questions/12850030/git-getting-all-previous-version-of-a-specific-file-folder
+
+set -e
+
+if ! git rev-parse --show-toplevel >/dev/null 2>&1 ; then
+	echo "Error: you must run this from within a git working directory" >&2
+	exit 1
+fi
+
+if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
+	echo "Usage: $0 <relative path to file> [<output directory>]" >&2
+	exit 2
+fi
+
+FILE_PATH="$1"
+
 EXPORT_TO=/tmp/all_versions_exported
-
-# take relative path to the file to inspect
-GIT_PATH_TO_FILE=$1
-
-# ---------------- don't edit below this line --------------
-
-USAGE="Please cd to the root of your git proj and specify path to file you with to inspect (example: $0 some/path/to/file)"
-
-# check if got argument
-if [ "${GIT_PATH_TO_FILE}" == "" ]; then
-    echo "error: no arguments given. ${USAGE}" >&2
-    exit 1
+if [ -n "$2" ]; then
+	EXPORT_TO="$2"
 fi
 
-# check if file exist
-if [ ! -f ${GIT_PATH_TO_FILE} ]; then
-    echo "error: File '${GIT_PATH_TO_FILE}' does not exist. ${USAGE}" >&2
-    exit 1
+FILE_NAME="$(basename '$FILE_PATH')"
+
+if [ ! -d "${EXPORT_TO}" ]; then
+    echo "Creating directory '${EXPORT_TO}'"
+    mkdir -p "${EXPORT_TO}"
 fi
 
-# extract just a filename from given relative path (will be used in result file names)
-GIT_SHORT_FILENAME=$(basename $GIT_PATH_TO_FILE)
+echo "Writing files to '$EXPORT_TO'"
+git log --diff-filter=d --date-order --reverse --format="%ad %H" --date=iso-strict "$FILE_PATH" | grep -v '^commit' | \
+	while read LINE; do \
+		COMMIT_DATE=`echo $LINE | cut -d ' ' -f 1`; \
+		COMMIT_SHA=`echo $LINE | cut -d ' ' -f 2`; \
+		printf '.' ; \
+		git cat-file -p "$COMMIT_SHA:$FILE_PATH" > "$EXPORT_TO/$COMMIT_DATE.$COMMIT_SHA.$FILE_NAME" ; \
+	done
+echo
 
-# create folder to store all revisions of the file
-if [ ! -d ${EXPORT_TO} ]; then
-    echo "creating folder: ${EXPORT_TO}"
-    mkdir ${EXPORT_TO}
-fi
-
-## uncomment next line to clear export folder each time you run script
-#rm ${EXPORT_TO}/*
-
-# reset coutner
-COUNT=0
-
-# iterate all revisions
-git rev-list --all --objects -- ${GIT_PATH_TO_FILE} | \
-    cut -d ' ' -f1 | \
-while read h; do \
-     COUNT=$((COUNT + 1)); \
-     COUNT_PRETTY=$(printf "%04d" $COUNT); \
-     COMMIT_DATE=`git show $h | head -3 | grep 'Date:' | awk '{print $4"-"$3"-"$6}'`; \
-     if [ "${COMMIT_DATE}" != "" ]; then \
-         git cat-file -p ${h}:${GIT_PATH_TO_FILE} > ${EXPORT_TO}/${COUNT_PRETTY}.${COMMIT_DATE}.${h}.${GIT_SHORT_FILENAME};\
-     fi;\
-done    
-
-# return success code
-echo "result stored to ${EXPORT_TO}"
 exit 0
+
