Lots of new scripts from Evan Hahn

diff --git a/bin/webserver b/bin/webserver
--- a/bin/webserver
+++ b/bin/webserver
@@ -1,10 +1,33 @@
-#!/bin/sh
-
+#!/usr/bin/env bash
 set -e
+set -u
+set -o pipefail
 
-if [ $# = 1 ]; then
-	cd "$1"
+# from https://codeberg.org/EvanHahn/dotfiles/src/commit/843b9ee13d949d346a4a73ccee2a99351aed285b/home/bin/bin/serveit
+
+port='8000'
+if [ $# -eq 1 ]; then
+  port="$1"
 fi
-open http://localhost:8000/
-python3 -m http.server 8000
 
+if command -v open >/dev/null 2>&1 ; then
+	open "http://localhost:$port/"
+fi
+
+if hash python3 2>/dev/null; then
+	exec python3 -m http.server "$port"
+elif hash python 2>/dev/null; then
+	major_version="$(python -c 'import platform as p;print(p.python_version_tuple()[0])')"
+	if [[ "$major_version" == '3' ]]; then
+		exec python -m http.server "$port"
+	else
+		exec python -m SimpleHTTPServer "$port"
+	fi
+elif hash ruby 2>/dev/null; then
+	exec ruby -run -e httpd . -p "$port"
+elif hash php 2>/dev/null; then
+	exec php -S "localhost:$port"
+else
+	echo 'unable to start HTTP server' 1>&2
+	exit 1
+fi
