fixes and improvements, mostly for pkg_comp

diff --git a/bin/server/pkg_comp_wrapper b/bin/server/pkg_comp_wrapper
--- a/bin/server/pkg_comp_wrapper
+++ b/bin/server/pkg_comp_wrapper
@@ -2,47 +2,52 @@
 
 set -eu
 
-PKG_COMP=/usr/pkg/sbin/pkg_comp
-PKGIN=/usr/pkg/bin/pkgin
+{
+	flock -n 9 || (echo "unable to obtain lock; is a build already running?" >&2 && exit 1)
 
-FAST=
-if [ $# -gt 0 ] && [ '-f' = "$1" ]; then
-	FAST="$1"
-	shift
-fi
+	PKG_COMP=/usr/pkg/sbin/pkg_comp
+	PKGIN=/usr/pkg/bin/pkgin
 
-PKGLIST="$@"
+	FAST=
+	if [ $# -gt 0 ] && [ '-f' = "$1" ]; then
+		FAST="$1"
+		shift
+	fi
 
-# do this early in case there's any problem loading it
-. ~/bin/util/pkg_comp_util.sh  # this will also grab util.sh
+	PKGLIST="$@"
 
-# do this early in case there are any invalid package names in the list
-echo "Initializing package name cache and checking for errors..."
-if [ -n "$PKGLIST" ]; then
-	# trick pkg_comp_util into using our shortened list
-	TEMPFILE="`tempname`"
-	echo "$PKGLIST" | tr ' ' "\n" > "$TEMPFILE"
-	PKG_LIST="$TEMPFILE"
-fi
-_uncached_desired_package_name >/dev/null || die $?
+	# do this early in case there's any problem loading it
+	. ~/bin/util/pkg_comp_util.sh  # this will also grab util.sh
 
-echo "Destroying old sandbox (and ignoring errors)..."
-$PKG_COMP sandbox-destroy || true
+	# do this early in case there are any invalid package names in the list
+	echo "Initializing package name cache and checking for errors..."
+	if [ -n "$PKGLIST" ]; then
+		# trick pkg_comp_util into using our shortened list
+		TEMPFILE="`tempname`"
+		echo "$PKGLIST" | tr ' ' "\n" > "$TEMPFILE"
+		PKG_LIST="$TEMPFILE"
+	fi
+	_uncached_desired_package_name >/dev/null || die $?
 
-echo "Creating new sandbox..."
-$PKG_COMP sandbox-create || die $? "Error creating sandbox"
+	echo "Destroying old sandbox (and ignoring errors)..."
+	$PKG_COMP sandbox-destroy || true
 
-echo "Building..."
-$PKG_COMP auto $FAST $PKGLIST || die $? "Error during 'auto' build"
+	echo "Creating new sandbox..."
+	$PKG_COMP sandbox-create || die $? "Error creating sandbox"
 
-echo "Checking that all desired packages exist..."
-_do_diff 'desired_package_names' 'current_package_files' || die $? "Some desired packages are missing"
+	echo "Building..."
+	$PKG_COMP auto $FAST $PKGLIST || die $? "Error during 'auto' build"
 
-echo "Destroying new sandbox..."
-$PKG_COMP sandbox-destroy || die $? "Error destroying sandbox"
+	echo "Checking that all desired packages exist..."
+	_do_diff 'desired_package_names' 'current_package_files' || die $? "Some desired packages are missing"
 
-echo "Running 'pkgin update'..."
-$PKGIN update || die $? "Error running 'pkgin update'"
+	echo "Destroying new sandbox..."
+	$PKG_COMP sandbox-destroy || die $? "Error destroying sandbox"
+
+	echo "Running 'pkgin update'..."
+	$PKGIN update || die $? "Error running 'pkgin update'"
+
+} 9>/tmp/pkg_comp_wrapper.flock
 
 echo "Done!"
 exit 0
